#!/bin/bash
docker rm -f mysql5.7-adventureworks
docker rm -f mysql5.6-adventureworks
docker rm -f mysql5.5-adventureworks
docker rm -f mysql8.0-adventureworks
docker rm -f mysql5.7-sakila
docker rm -f mysql5.6-sakila
docker rm -f mysql5.5-sakila
docker rm -f mysql8.0-sakila
docker rm -f mysql5.7-world_x
docker rm -f mysql8.0-world_x
docker rm -f mysql5.7-siemens-test-db
docker rm -f mysql5.6-siemens-test-db
docker rm -f mysql5.5-siemens-test-db
docker rm -f mysql8.0-siemens-test-db
docker rm -f mariadb10.1-adventureworks
docker rm -f mariadb10.2-adventureworks
docker rm -f mariadb10.3-adventureworks
docker rm -f mariadb10.4-adventureworks
docker rm -f postgres9.6-adventureworks
docker rm -f postgres9.6-sakila
docker rm -f mssql2017-adventureworks
docker rm -f mssql2019-adventureworks
docker rm -f mysql8.0-jaffle
docker rm -f mysql5.7-jaffle
docker rm -f mysql5.6-jaffle
docker rm -f mysql5.5-jaffle
